resolver: lts-8.9
packages: []
extra-deps:
- github: purescript/purescript
  commit: ac57b5d74a0086c48d377c28a6912c2cb6359f6a
- github: snoyberg/purify
  commit: 66a60fba14ca5bc749dee83e1286e0406ddffae6
- pipes-http-1.0.5
